### PR TITLE
Create what_he_said

### PR DESCRIPTION
**Pull request by EpicAwesomeWolf**

### CODE REVIEW

**Comment by nekonez** [comment]
what is this example good for? :thinking:

**Comment by EpicAwesomeWolf** [comment]
i'm not too sure but i saw it in another bot and i thought it would be a good use of a `.includes()`

**Comment by nekonez** [comment]
hmm

**Comment by EpicAwesomeWolf** [comment]
i could make it instead of ^ it would be if it included a link it would alert the server
idrk

**Pull request merged**
